apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/eyalbe4/maven-example-single-module:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/eyalbe4/maven-example-single-module:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: maven-example-single-module
        chartPath: charts/maven-example-single-module
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/eyalbe4/maven-example-single-module"
          image.tag: "{{.TAG}}"
